name: 自動化爬蟲

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜執行
  workflow_dispatch:     # 允許手動觸發

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v3
        
      - name: 設定Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝依賴
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 執行爬蟲
        run: python main.py
        
      - name: 配置Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: 提交爬取的數據
        run: |
          git add data/
          git commit -m "自動更新資料 $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
